config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'

  devise_for :admins

  root to: "bloopers#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  post 'search', to: 'search#search'
  resources :bloopers, :actors, :movies, :tvs, :genres, only: [:index, :show], :concerns => :paginatable

  namespace :admin do
    get '/' => '/admin/base#index'

    namespace :tmdb do
      get 'genres' => '/admin/tmdb#genres_list'
      get 'import_genres' => '/admin/tmdb#import_genres'
      post 'person_search' => '/admin/tmdb#person_search'
      post 'person' => '/admin/tmdb#person'
      post 'movie_search' => '/admin/tmdb#movie_search'
      post 'movie' => '/admin/tmdb#movie'
      post 'tv' => '/admin/tmdb#tv'
      post 'add_person' => '/admin/tmdb#add_person'
    end

    resources :movie_types, :genres, :actors, :movies, :bloopers, :admins, :visits, :concerns => :paginatable
  end

end

app/models/blooper.rb
class Blooper < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :movie

  validates :name, :movie_id, :video_link, presence: true
  validates :name, :video_link, length: { maximum: 256 }

end

app/controllers/admin/bloopers_controller.rb
class Admin::BloopersController < Admin::BaseController
  before_action :set_admin_blooper, only: [:show, :edit, :update, :destroy]

  # GET /admin/bloopers
  # GET /admin/bloopers.json
  def index
    @admin_bloopers = Blooper.includes(:movie).order(created_at: :desc).page(params[:page]).per(20)
  end

  # GET /admin/bloopers/1
  # GET /admin/bloopers/1.json
  def show
  end

  # GET /admin/bloopers/new
  def new
    @admin_blooper = Blooper.new
  end

  # GET /admin/bloopers/1/edit
  def edit
  end

  # POST /admin/bloopers
  # POST /admin/bloopers.json
  def create
    @admin_blooper = Blooper.new(admin_blooper_params)

    respond_to do |format|
      if @admin_blooper.save
        format.html { redirect_to [:admin, @admin_blooper], notice: 'Blooper was successfully created.' }
        format.json { render :show, status: :created, location: @admin_blooper }
      else
        format.html { render :new }
        format.json { render json: @admin_blooper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/bloopers/1
  # PATCH/PUT /admin/bloopers/1.json
  def update
    respond_to do |format|
      if @admin_blooper.update(admin_blooper_params)
        format.html { redirect_to [:admin, @admin_blooper], notice: 'Blooper was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_blooper }
      else
        format.html { render :edit }
        format.json { render json: @admin_blooper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/bloopers/1
  # DELETE /admin/bloopers/1.json
  def destroy
    @admin_blooper.destroy
    respond_to do |format|
      format.html { redirect_to admin_bloopers_url, notice: 'Blooper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blooper
      @admin_blooper = Blooper.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blooper_params
      params.require(:blooper).permit(:name, :video_link, :movie_id, :description, :status)

    end
end

app/controllers/bloopers_controller.rb
class BloopersController < ApplicationController
  include BloopersHelper
  # GET /bloopers
  def index
    Rails.cache.write(cache_key_for_bloopers, Blooper.includes(:movie).where(status: :true).order(created_at: :desc), expires_in: 1.hours) until Rails.cache.read(cache_key_for_bloopers)
    bloopers = Rails.cache.read(cache_key_for_bloopers)
    @bloopers = prepare_reverse_pagination bloopers
  end

  # GET /bloopers/1
  def show
    key = "blooper-#{params[:id]}"
    Rails.cache.write(key, (Blooper.friendly.where(slug: params[:id], status: :true).first or not_found), expires_in: 2.hours) until Rails.cache.read(key)
    @blooper = Rails.cache.read(key)

    ahoy.track 'Viewed blooper', id: @blooper.id, title: @blooper.name

    set_meta_tags description: @blooper.description,
                  og: {
                      title:    "Bloopers | #{@blooper.name}",
                      type:     'website',
                      url:      blooper_url(@blooper),
                      video:    "https://www.youtube.com/embed/#{@blooper.video_link}?rel=0"
                  }
  end

end

app/helpers/admin/bloopers_helper.rb
module Admin::BloopersHelper
end

app/helpers/bloopers_helper.rb
module BloopersHelper
  def cache_key_for_bloopers
    count          = Blooper.where(status: :true).count
    max_updated_at = Blooper.where(status: :true).maximum(:updated_at).try(:utc).try(:to_s, :number)
    "bloopers/all-#{count}-#{max_updated_at}-#{params[:page]}"
  end
end

app/views/admin/bloopers/_form.html.erb
<div class="row" id="blooper">
  <%= form_for [:admin, @admin_blooper], :html => {:class => 'col s12'} do |f| %>
    <% if @admin_blooper.errors.any? %>
      <% @admin_blooper.errors.full_messages.each do |message| %>
        <script>
          Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= message %>', 4000, 'red darken-1');
        </script>
      <% end %>
    <% end %>

    <div class="row">
      <div class="input-field col s8">
        <%= f.text_field :video_link %>
        <%= f.label :video_link %>
      </div>
      <div class="col s4">
        <a id="show-video" class="waves-effect waves-light btn">Show</a>
      </div>
    </div>
    <div class="video-container blooper-video">
      <iframe id="blooper-video-iframe" width="853" height="480" src="" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.collection_select(:movie_id, Movie.all.order(created_at: :desc), :id, :name,  include_blank: 'Select movie') %>
        <%= f.label :movie %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :description, class: 'materialize-textarea' %>
        <%= f.label :description %>
      </div>
    </div>
    <div class="row">
      <div class="switch">
        <label>
          Off
          <%= f.check_box :status %>
          <span class="lever"></span>
          On
        </label>
      </div>
    </div>

    <button class="btn waves-effect waves-light btn-large green" type="submit" name="action">
      Submit
    </button>
  <% end %>
</div>

app/views/admin/bloopers/edit.html.erb
<div class="row">
  <h5>Editing Blooper</h5>

  <%= render 'form' %>

  <%= link_to 'Show', admin_blooper_path(@admin_blooper) %> |
  <%= link_to 'Back', admin_bloopers_path %>
</div>

app/views/admin/bloopers/index.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h5>Listing Bloopers</h5>
    </div>
    <div class="divider"></div>

    <table class="hoverable centered responsive-table">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Movie</th>
        <th>Video</th>
        <th>Active</th>
        <th colspan="3">Options</th>
      </tr>
      </thead>

      <tbody>
      <% @admin_bloopers.each do |admin_blooper| %>
        <tr>
          <td><%= admin_blooper.id %></td>
          <td><%= admin_blooper.name %></td>
          <td><%= admin_blooper.movie.name %></td>
          <td><%= admin_blooper.status.to_s.capitalize %></td>
          <td><%= link_to 'View', [:admin, admin_blooper], class: 'waves-effect waves-light btn green' %></td>
          <td><%= link_to 'Edit', edit_admin_blooper_path(admin_blooper), class: 'waves-effect waves-light btn orange' %></td>
          <td><%= link_to 'Delete', [:admin, admin_blooper], method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <a class="btn-floating btn-large waves-effect waves-light purple darken-3" href="<%= new_admin_blooper_path %>"><i class="material-icons">add</i></a>
    <div class="col s12 m10 l10 right">
      <%= paginate @admin_bloopers %>
    </div>
  </div>
</div>

app/views/admin/bloopers/new.html.erb
<div class="row">
  <h5>New Blooper</h5>

  <%= render 'form' %>

  <%= link_to 'Back', admin_bloopers_path %>
</div>

app/views/admin/bloopers/show.html.erb
<div class="row">
  <div class="col s12 m7">
    <div class="video-container">
      <iframe width="853" height="480" src="//www.youtube.com/embed/<%= @admin_blooper.video_link %>?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
    <div>
      <p>Name: <%= @admin_blooper.name %></p>
      <p>Active: <%= @admin_blooper.status %></p>
      <p>Description:</p>
      <p>
        <%= @admin_blooper.description %>
      </p>
    </div>
    <div>
      <%= link_to 'Edit', edit_admin_blooper_path(@admin_blooper) %>
      <%= link_to 'Back', admin_bloopers_path %>
    </div>
  </div>
  <div class="col s12 m5">
    <div>
      <blockquote>
        Movie:
      </blockquote>
      <div class="col s12 white">
        <a href="<%= admin_movie_path(@admin_blooper.movie) %>">
          <div class="card-panel grey lighten-5 z-depth-1">
            <div class="row valign-wrapper">
              <div class="col s3">
                <% if !@admin_blooper.movie.image.blank? %>
                  <img src="<%= @admin_blooper.movie.image %>" alt="" class="responsive-img">
                <% else %>
                  <%= image_tag 'default_profile_picture.png', class: "responsive-img" %>
                <% end %>
              </div>
              <div class="col s9">
                <span class="black-text">
                    <%= @admin_blooper.movie.name %>
                </span>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

    <div>
      <% if @admin_blooper.movie.genres.any? %>
      <blockquote>
        Genres:
      </blockquote>
      <div class="collection">
        <% @admin_blooper.movie.genres.each do |genre| %>
          <a href="<%= admin_genre_path(genre) %>" class="collection-item"><%= genre.name %></a>
        <% end %>
      </div>
    <% end %>
    </div>

    <div>
      <% if @admin_blooper.movie.actors.any? %>
      <blockquote>
        Actors:
      </blockquote>
      <% @admin_blooper.movie.actors.each do |actor| %>
        <div class="col s12">
          <a href="<%= admin_actor_path(actor) %>">
            <div class="card-panel grey lighten-5 z-depth-1">
              <div class="row valign-wrapper">
                <div class="col s3">
                  <% if !actor.image.blank? %>
                    <img src="<%= actor.image %>" alt="" class="circle responsive-img">
                  <% else %>
                    <%= image_tag 'default_profile_picture.png', class: "circle responsive-img" %>
                  <% end %>
                </div>
                <div class="col s9">
                <span class="black-text">
                    <%= actor.name %>
                </span>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>