config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'

  devise_for :admins

  root to: "bloopers#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  post 'search', to: 'search#search'
  resources :bloopers, :actors, :movies, :tvs, :genres, only: [:index, :show], :concerns => :paginatable

  namespace :admin do
    get '/' => '/admin/base#index'

    namespace :tmdb do
      get 'genres' => '/admin/tmdb#genres_list'
      get 'import_genres' => '/admin/tmdb#import_genres'
      post 'person_search' => '/admin/tmdb#person_search'
      post 'person' => '/admin/tmdb#person'
      post 'movie_search' => '/admin/tmdb#movie_search'
      post 'movie' => '/admin/tmdb#movie'
      post 'tv' => '/admin/tmdb#tv'
      post 'add_person' => '/admin/tmdb#add_person'
    end

    resources :movie_types, :genres, :actors, :movies, :bloopers, :admins, :visits, :concerns => :paginatable
  end

end

app/views/shared/_alerts.html.erb
<% if notice %>
  <script>
    Materialize.toast('<i class="material-icons">done</i> &nbsp;&nbsp;&nbsp; <%= notice %>', 4000, 'green darken-1');
  </script>
<% end %>

<% if alert %>
  <script>
    Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= alert %>', 4000, 'red darken-1');
  </script>
<% end %>

app/views/shared/_comments.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES * * */
  var disqus_shortname = 'bloopersrocks';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<footer class="page-footer blue-grey darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Bloopers</h5>
        <p class="grey-text text-lighten-4">Best bloopers!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="<%= pages_about_path %>">About</a></li>
          <li><a class="grey-text text-lighten-3" href="<%= pages_contact_path %>">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © <%= Time.current.year %> Bloopers
      <a class="grey-text text-lighten-4 right" target="_blank" href="http://4code.pl">4Code</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="amber darken-3">
  <div class="nav-wrapper">
    <%= link_to(image_tag('movie-clapper-board-64-130297.png', alt: "Bloopers", title: "Bloopers") + raw('<span id="logo-text">Bloopers</span>'), root_path, class: 'brand-logo') %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <%= render 'shared/menu_links' %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <%= render 'shared/menu_links' %>
    </ul>
  </div>
</nav>

<script>
  $(".button-collapse").sideNav();
</script>

app/views/shared/_menu_links.html.erb
<li class="search hide-on-med-and-down">
  <form>
    <div class="input-field">
      <input id="search" type="search" required autocomplete="off">
      <label for="search"><i class="material-icons">search</i></label>
      <i class="material-icons">close</i>
    </div>
    <div id="results" class="z-depth-5">
      <div id="search-preloader" class="preloader-wrapper small active">
        <div class="spinner-layer spinner-blue-only">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
      <div id="results-data"></div>
    </div>
  </form>
</li>
<%= active_link_to 'Bloopers', bloopers_path, :wrap_tag => :li %>
<%= active_link_to 'Actors', actors_path, :wrap_tag => :li %>
<%= active_link_to 'Movies', movies_path, :wrap_tag => :li %>
<%= active_link_to 'TV', tvs_path, :wrap_tag => :li %>
<%= active_link_to 'Genres', genres_path, :wrap_tag => :li %>

app/views/shared/_social_buttons.html.erb
<div class="fb-like"
     data-href="<%= link ||= request.original_url %>"
     data-layout="button_count"
     data-action="like"
     data-show-faces="false"
     data-share="true">
</div>