config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'

  devise_for :admins

  root to: "bloopers#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  post 'search', to: 'search#search'
  resources :bloopers, :actors, :movies, :tvs, :genres, only: [:index, :show], :concerns => :paginatable

  namespace :admin do
    get '/' => '/admin/base#index'

    namespace :tmdb do
      get 'genres' => '/admin/tmdb#genres_list'
      get 'import_genres' => '/admin/tmdb#import_genres'
      post 'person_search' => '/admin/tmdb#person_search'
      post 'person' => '/admin/tmdb#person'
      post 'movie_search' => '/admin/tmdb#movie_search'
      post 'movie' => '/admin/tmdb#movie'
      post 'tv' => '/admin/tmdb#tv'
      post 'add_person' => '/admin/tmdb#add_person'
    end

    resources :movie_types, :genres, :actors, :movies, :bloopers, :admins, :visits, :concerns => :paginatable
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :movie_genres, dependent: :destroy
  has_many :movies, through: :movie_genres

  validates :imdb_id, :name, presence: true
  validates :imdb_id, numericality: { only_integer: true }, length: { maximum: 8 }
  validates :name, length: { maximum: 256 }

  # import genres
  # genres - array
  def self.import( genres )
    if !genres.nil?
      genres.each do |genre|
        g = self.find_by(name: genre['name'])
        if g.nil?
          self.create(name: genre['name'], imdb_id: genre['id'], status: true)
        end
      end
    end
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :set_admin_genre, only: [:show, :edit, :update, :destroy]

  # GET /admin/genres
  # GET /admin/genres.json
  def index
    @admin_genres = Genre.order(:name).page(params[:page]).per(10)
  end

  # GET /admin/genres/1
  # GET /admin/genres/1.json
  def show
  end

  # GET /admin/genres/new
  def new
    @admin_genre = Genre.new
  end

  # GET /admin/genres/1/edit
  def edit
  end

  # POST /admin/genres
  # POST /admin/genres.json
  def create
    @admin_genre = Genre.new(admin_genre_params)

    respond_to do |format|
      if @admin_genre.save
        format.html { redirect_to [:admin, @admin_genre], notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @admin_genre }
      else
        format.html { render :new }
        format.json { render json: @admin_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/genres/1
  # PATCH/PUT /admin/genres/1.json
  def update
    respond_to do |format|
      if @admin_genre.update(admin_genre_params)
        format.html { redirect_to [:admin, @admin_genre], notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_genre }
      else
        format.html { render :edit }
        format.json { render json: @admin_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/genres/1
  # DELETE /admin/genres/1.json
  def destroy
    @admin_genre.destroy
    respond_to do |format|
      format.html { redirect_to admin_genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_genre
      @admin_genre = Genre.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_genre_params
      params.require(:genre).permit(:name, :imdb_id, :status)

    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  include GenresHelper

  # GET /genres
  def index
    Rails.cache.write(cache_key_for_genres, Genre.where(status: true).order(name: :asc)) until Rails.cache.read(cache_key_for_genres)
    @genres = Rails.cache.read(cache_key_for_genres)
  end

  # GET /genres/1
  def show
    key = "genre-#{params[:id]}"
    Rails.cache.write(key, (Genre.includes(movies: [:movie_type, :bloopers]).friendly.where(slug: params[:id], status: :true).first  or not_found), expires_in: 2.hours) until Rails.cache.read(key)
    @genre = Rails.cache.read(key)

    ahoy.track 'Viewed genre', id: @genre.id, title: @genre.name
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
  def cache_key_for_genres
    # count          = Genre.count
    # max_updated_at = Genre.maximum(:updated_at).try(:utc).try(:to_s, :number)
    # "genres/all-#{count}-#{max_updated_at}"
    'genres/all'
  end
end

app/views/admin/genres/_form.html.erb
<div class="row">
  <%= form_for [:admin, @admin_genre], :html => {:class => 'col s12'} do |f| %>
    <% if @admin_genre.errors.any? %>
      <% @admin_genre.errors.full_messages.each do |message| %>
        <script>
          Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= message %>', 4000, 'red darken-1');
        </script>
      <% end %>
    <% end %>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :imdb_id %>
        <%= f.label :imdb_id %>
      </div>
    </div>
    <div class="row">
      <div class="switch">
        <label>
          Off
          <%= f.check_box :status %>
          <span class="lever"></span>
          On
        </label>
      </div>
    </div>

    <button class="btn waves-effect waves-light btn-large green" type="submit" name="action">
      Submit
    </button>
  <% end %>
</div>

app/views/admin/genres/edit.html.erb
<div class="row">
  <h5>Editing Genre</h5>

  <%= render 'form' %>

  <%= link_to 'Show', admin_genre_path(@admin_genre) %> |
  <%= link_to 'Back', admin_genres_path %>
</div>

app/views/admin/genres/index.html.erb
<div class="row">
  <div class="col s12 m8 l8">
    <div class="section">
      <h5>Listing Genres</h5>
    </div>
    <div class="divider"></div>

    <table class="hoverable centered responsive-table">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>IMDB ID</th>
        <th>Active</th>
        <th colspan="3">Options</th>
      </tr>
      </thead>

      <tbody>
      <% @admin_genres.each do |admin_genre| %>
        <tr>
          <td><%= admin_genre.id %></td>
          <td><%= admin_genre.name %></td>
          <td><%= admin_genre.imdb_id %></td>
          <td><%= admin_genre.status.to_s.capitalize %></td>
          <td><%= link_to 'View', [:admin, admin_genre], class: 'waves-effect waves-light btn green' %></td>
          <td><%= link_to 'Edit', edit_admin_genre_path(admin_genre), class: 'waves-effect waves-light btn orange' %></td>
          <td><%= link_to 'Delete', [:admin, admin_genre], method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <a class="btn-floating btn-large waves-effect waves-light purple darken-3" href="<%= new_admin_genre_path %>"><i class="material-icons">add</i></a>
    <a class="btn-floating btn-large waves-effect waves-light red darken-3" href="<%= admin_tmdb_import_genres_path %>"><i class="material-icons">import_export</i></a>
    <div class="col s12 m8 l8 right">
      <%= paginate @admin_genres %>
    </div>
  </div>
</div>

app/views/admin/genres/new.html.erb
<div class="row">
  <div class="col s8">
    <h5>New Genre</h5>

    <%= render 'form' %>

    <%= link_to 'Back', admin_genres_path %>
  </div>
</div>

app/views/admin/genres/show.html.erb
<p class="flow-text">Name: <%= @admin_genre.name %></p>
<p class="flow-text">Imdb id: <%= @admin_genre.imdb_id %></p>
<p class="flow-text">Active: <%= @admin_genre.status %></p>

<% if @admin_genre.movies.any? %>
  <p class="flow-text">Movies:</p>
  <% @admin_genre.movies.each do |movie| %>
    <p class="flow-text"><%= movie.name %></p>
  <% end %>
<% end %>


<%= link_to 'Edit', edit_admin_genre_path(@admin_genre) %> |
<%= link_to 'Back', admin_genres_path %>