config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'

  devise_for :admins

  root to: "bloopers#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  post 'search', to: 'search#search'
  resources :bloopers, :actors, :movies, :tvs, :genres, only: [:index, :show], :concerns => :paginatable

  namespace :admin do
    get '/' => '/admin/base#index'

    namespace :tmdb do
      get 'genres' => '/admin/tmdb#genres_list'
      get 'import_genres' => '/admin/tmdb#import_genres'
      post 'person_search' => '/admin/tmdb#person_search'
      post 'person' => '/admin/tmdb#person'
      post 'movie_search' => '/admin/tmdb#movie_search'
      post 'movie' => '/admin/tmdb#movie'
      post 'tv' => '/admin/tmdb#tv'
      post 'add_person' => '/admin/tmdb#add_person'
    end

    resources :movie_types, :genres, :actors, :movies, :bloopers, :admins, :visits, :concerns => :paginatable
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :movie_type
  has_many :movie_genres, dependent: :destroy
  has_many :genres, through: :movie_genres
  has_many :movie_actors, dependent: :destroy
  has_many :actors, through: :movie_actors
  has_many :bloopers

  validates :tmdb_id, :name, :description, :image, :movie_type_id, :genres, presence: true
  validates :tmdb_id, numericality: { only_integer: true }
  validates :name, :image, :tmdb_id, :imdb_id, length: { maximum: 256 }

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'english'
      indexes :description, analyzer: 'english'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^10', 'description']
          }
        }
      }
    )
  end

  def as_indexed_json(options = {})
    self.as_json({
         only: [:name, :description, :image, :slug],
         include: {
             movie_type: { only: :name }
         }
     })
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  before_action :set_admin_movie, only: [:show, :edit, :update, :destroy]

  # GET /admin/movies
  # GET /admin/movies.json
  def index
    @admin_movies = Movie.includes(:movie_type).order(:name).page(params[:page]).per(10)
  end

  # GET /admin/movies/1
  # GET /admin/movies/1.json
  def show
  end

  # GET /admin/movies/new
  def new
    @admin_movie = Movie.new
  end

  # GET /admin/movies/1/edit
  def edit
  end

  # POST /admin/movies
  # POST /admin/movies.json
  def create
    @admin_movie = Movie.new(admin_movie_params)

    respond_to do |format|
      if @admin_movie.save
        format.html { redirect_to [:admin, @admin_movie], notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @admin_movie }
      else
        format.html { render :new }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/movies/1
  # PATCH/PUT /admin/movies/1.json
  def update
    respond_to do |format|
      if @admin_movie.update(admin_movie_params)
        format.html { redirect_to [:admin, @admin_movie], notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_movie }
      else
        format.html { render :edit }
        format.json { render json: @admin_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/movies/1
  # DELETE /admin/movies/1.json
  def destroy
    @admin_movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_movie
      @admin_movie = Movie.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_movie_params
      params.require(:movie).permit(:name, :tmdb_id, :imdb_id, :image, :description, :status,
                                    :release_date, :vote_average, :movie_type_id,
                                    actor_ids: [], genre_ids: [])

    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MoviesHelper
  # GET /movies
  def index
    until Rails.cache.read(cache_key_for_movies)
      movie = MovieType.find_by_name('Movie')
      Rails.cache.write(cache_key_for_movies, Movie.where(status: :true, movie_type: movie).order(created_at: :desc))
    end
    movies = Rails.cache.read(cache_key_for_movies)
    @movies = prepare_reverse_pagination movies, 9
  end

  # GET /movies/1
  def show
    key = "movie-#{params[:id]}"
    Rails.cache.write(key, (Movie.friendly.where(slug: params[:id], status: :true).first  or not_found), expires_in: 2.hours) until Rails.cache.read(key)
    @movie = Rails.cache.read(key)

    ahoy.track 'Viewed Movie', id: @movie.id, title: @movie.name

    set_meta_tags description: @movie.description,
                  og: {
                      title:    "Bloopers | #{@movie.name}",
                      type:     'website',
                      url:      movie_url(@movie),
                      image:    @movie.image
                  }
  end

end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def cache_key_for_movies
    count          = Movie.where(status: :true).count
    max_updated_at = Movie.where(status: :true).maximum(:updated_at).try(:utc).try(:to_s, :number)
    "movies/all-#{count}-#{max_updated_at}-#{params[:page]}"
  end
end

app/views/admin/movies/_form.html.erb
<div id="movies" class="row">
  <div class="col s12 m6">
    <%= form_for [:admin, @admin_movie] do |f| %>
      <% if @admin_movie.errors.any? %>
        <% @admin_movie.errors.full_messages.each do |message| %>
          <script>
            Materialize.toast('<i class="material-icons">error_outline</i> &nbsp;&nbsp;&nbsp; <%= message %>', 4000, 'red darken-1');
          </script>
        <% end %>
      <% end %>

      <div class="row">
        <div class="input-field col s12">
          <%= f.collection_select(:movie_type_id, MovieType.all, :id, :name) %>
          <%= f.label :movie_type %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <%= f.label :name %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :image %>
          <%= f.label :image %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :tmdb_id %>
          <%= f.label :tmdb_id %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :imdb_id %>
          <%= f.label :imdb_id %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :description, class: 'materialize-textarea' %>
          <%= f.label :description %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :release_date, class: 'datepicker' %>
          <%= f.label :release_date %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :vote_average %>
          <%= f.label :vote_average %>
        </div>
      </div>

      <div class="row">
        <div class="col s6">
          <blockquote>
            Actors:
          </blockquote>
          <div class="row actors">
            <div class="col s12" id="actors-list">
              <%= f.collection_check_boxes(:actor_ids, Actor.order(:name), :id, :name) %>
            </div>
          </div>
        </div>

        <div class="col s6">
          <blockquote>
            Genres:
          </blockquote>
          <div class="row genres actors">
            <div class="col s12">
              <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="switch">
          <label>
            Off
            <%= f.check_box :status %>
            <span class="lever"></span>
            On
          </label>
        </div>
      </div>

      <button class="btn waves-effect waves-light btn-large green" type="submit" name="action">
        Submit
      </button>
    <% end %>
  </div>
  <div class="col s12 m6">
    <h6>Search</h6>

    <div class="row">
      <a id="btn-search" class="waves-effect waves-light btn right">Search</a>

      <div class="input-field col s8 right">
        <i class="material-icons prefix">movie</i>
        <input id="search" type="text" class="validate">
        <label for="search">Movie or TV Name</label>
      </div>
    </div>

    <div class="row" id="result-tabs">
      <div class="col s10 right">
        <ul class="tabs">
          <li class="tab col s3"><a class="active" href="#movies-tab">Movies</a></li>
          <li class="tab col s3"><a href="#tv-tab">TV</a></li>
        </ul>
      </div>
      <div id="movies-tab" class="col s12">
        <div class="results" ></div>
      </div>
      <div id="tv-tab" class="col s12">
        <div class="results" ></div>
      </div>
    </div>

    <div class="row" id="movie-details">
      <div class="col s12 m10 right">
        <div class="card">
          <div class="card-image">
            <img src="" alt="image" id="movie-details-image">
            <span class="card-title"></span>
          </div>
          <div class="card-content">
            <p></p>
          </div>
          <div class="card-action">
            <a href="#" id="copy-data">Copy data</a>
          </div>
        </div>
        <blockquote>
          Actors:
        </blockquote>
        <div class="results" ></div>
      </div>
    </div>

    <div id="spinner" class="col s12 center">
      <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>

        <div class="spinner-layer spinner-red">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>

        <div class="spinner-layer spinner-yellow">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>

        <div class="spinner-layer spinner-green">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/movies/edit.html.erb
<div class="row">
  <h5>Editing Movie</h5>

  <%= render 'form' %>

  <%= link_to 'Show', admin_movie_path(@admin_movie) %> |
  <%= link_to 'Back', admin_movies_path %>
</div>

app/views/admin/movies/index.html.erb
<div class="row">
  <div class="col s12 m10 l10">
    <div class="section">
      <h5>Listing Movies</h5>
    </div>
    <div class="divider"></div>

    <table class="hoverable centered responsive-table">
      <thead>
      <tr>
        <th>#</th>
        <th width="10%">Image</th>
        <th>Name</th>
        <th>Type</th>
        <th>Active</th>
        <th colspan="3">Options</th>
      </tr>
      </thead>

      <tbody>
      <% @admin_movies.each do |admin_movie| %>
        <tr>
          <td><%= admin_movie.id %></td>
          <td><% if !admin_movie.image.blank? %>
              <img src="<%= admin_movie.image %>" alt="" class="responsive-img">
            <% end %>
          </td>
          <td><%= admin_movie.name %></td>
          <td><%= admin_movie.movie_type.name %></td>
          <td><%= admin_movie.status.to_s.capitalize %></td>
          <td><%= link_to 'View', [:admin, admin_movie], class: 'waves-effect waves-light btn green' %></td>
          <td><%= link_to 'Edit', edit_admin_movie_path(admin_movie), class: 'waves-effect waves-light btn orange' %></td>
          <td><%= link_to 'Delete', [:admin, admin_movie], method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <a class="btn-floating btn-large waves-effect waves-light purple darken-3" href="<%= new_admin_movie_path %>"><i class="material-icons">add</i></a>
    <div class="col s12 m10 l10 right">
      <%= paginate @admin_movies %>
    </div>
  </div>
</div>

app/views/admin/movies/new.html.erb
<div class="row">
    <h5>New Movie</h5>

    <%= render 'form' %>

    <%= link_to 'Back', admin_movies_path %>
</div>

app/views/admin/movies/show.html.erb
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <img src="<%= @admin_movie.image %>" alt="" class="circle responsive-img">
        <span class="card-title"><%= @admin_movie.name %></span>
      </div>
      <div class="card-content">
        <p>Tmdb_id: <%= @admin_movie.tmdb_id %></p>

        <p>Imdb_id: <%= @admin_movie.imdb_id %></p>

        <p>Active: <%= @admin_movie.status %></p>

        <p>Relases date: <%= @admin_movie.release_date %></p>

        <p>Vote average: <%= @admin_movie.vote_average %></p>

        <p>Description:</p>

        <p>
          <%= @admin_movie.description %>
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_admin_movie_path(@admin_movie) %>
        <%= link_to 'Back', admin_movies_path %>
      </div>
    </div>
  </div>
  <div class="col s12 m5">
    <p>
      <% if @admin_movie.genres.any? %>
      <blockquote>
        Genres:
      </blockquote>
      <div class="collection">
        <% @admin_movie.genres.each do |genre| %>
          <a href="<%= admin_genre_path(genre) %>" class="collection-item"><%= genre.name %></a>
        <% end %>
      </div>
    <% end %>
    </p>
    <p>
      <% if @admin_movie.actors.any? %>
      <blockquote>
        Actors:
      </blockquote>
      <% @admin_movie.actors.each do |actor| %>
        <div class="col s12 white">
          <a href="<%= admin_actor_path(actor) %>">
            <div class="card-panel grey lighten-5 z-depth-1">
              <div class="row valign-wrapper">
                <div class="col s3">
                  <% if !actor.image.blank? %>
                    <img src="<%= actor.image %>" alt="" class="circle responsive-img">
                  <% else %>
                    <%= image_tag 'default_profile_picture.png', class: "circle responsive-img" %>
                  <% end %>
                </div>
                <div class="col s9">
                <span class="black-text">
                    <%= actor.name %>
                </span>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
    </p>
    <p>
      <% if @admin_movie.bloopers.any? %>
      <blockquote>
        Bloopers:
      </blockquote>
      <div class="collection">
        <% @admin_movie.bloopers.each do |blooper| %>
          <a href="<%= admin_blooper_path(blooper) %>" class="collection-item"><%= blooper.name %></a>
        <% end %>
      </div>
    <% end %>
    </p>
  </div>
</div>